# SPDX-FileCopyrightText: 2023 Filipe Laíns
#
# SPDX-License-Identifier: MIT

name: docs

on:
  push:
  pull_request:
    branches:
      - main
      - release-*
    paths:
      - docs/**
      - CHANGELOG.rst

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: actions/checkout@v3
      - run: python -m pip install nox
      - run: nox -s docs
